# estimate_trip_cost.estimate_trip_cost { #travelpy.estimate_trip_cost.estimate_trip_cost }

```python
estimate_trip_cost.estimate_trip_cost(distance, fuel_price, efficiency)
```

Calculate the total fuel cost of a trip in Canada (Metric units), 
including a contingency fee for long trips.

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                                        | Default    |
|------------|--------|--------------------------------------------------------------------|------------|
| distance   | float  | The distance of the trip in kilometers (km).                       | _required_ |
| fuel_price | float  | The price of fuel per liter (CAD/L).                               | _required_ |
| efficiency | float  | The fuel efficiency of the vehicle in kilometers per liter (km/L). | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                 |
|--------|--------|-------------------------------------------------------------|
|        | float  | The estimated cost of the trip rounded to 2 decimal places. |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                                                            |
|--------|------------|------------------------------------------------------------------------|
|        | ValueError | If distance, fuel_price, or efficiency are less than or equal to zero. |

## Examples {.doc-section .doc-section-examples}

```python
>>> estimate_trip_cost(150, 1.7, 12)
21.25
>>> estimate_trip_cost(900, 1.7, 12)
146.62
```